module ComposicaoFuncao1 where
-- REGRA: O RETORNO DE UMA É A ENTRADA DE OUTRA, E O TIPO DE SAÍDA DA ÚLTIMA A SER CHAMADA
-- É O TIPO DE SAÍDA GERAL (QUANDO DAMOS O COMANDO :t PARA VER A ASSINATURA DA FUNÇÃO)

